Dodajem zadatak 1
JovanPEndava/jovan_penic_java_zadaci pull request #1
Opened 2019-10-08 11:39 UTC by JovanPEndava

2019-10-08 15:01 UTC, BoskoNikolic requested changes
Nemam neke prevelike zamerke na kod ali razmisli malo o tome da ako neko drugi koristi ovaj programcic sta sve moze da podje naopako(npr. uneo sam brojeve u ime i prezime, Da li je to korekto?).
Pogledaj komentare u kodu i pokusaj da ih ispravis.
Pogledaj listu bug-ova u issues tab-u.

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Kuca.java
> +            System.out.println("Greska, niste pravilno uneli podatke.");
Bilo bi dobro da se jasnije definise koji podaci nisu korektno uneti.

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Kuca.java
> +        if (povrsinaOkucnice >= 0) {
Jel moze da bude jednaka nuli?

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Main.java
> + */
Stavi sve pod isti komentar

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Main.java
> +// Author: Jovan Penic
@author  (pogledaj napomenu zadatka)

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Main.java
> +        Nekretnina kuca = new Kuca("Zivojina Misica br. 17", 3,130.2, vlasnikKuce, 30);
Pogledaj Issues tab issue br 2.

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Kuca.java
> +            System.out.println("Greska, niste pravilno uneli podatke.");
Pogledaj issues tab issue br 1.

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/MainTest.java
> +        int choice = 0;
Nema potreba da se ovde inicijalizuje vrednost, posto se nece nigde koristiti.

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/MainTest.java
> +package zadatak1;
Obzirom da ces imati dovoljno stvari za izmenu, izbaci ovu klasu iz naredne verzije (taman da vidis kako se brisu file-ovi).

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Nekretnina.java
> +    }
Ovde si mogao koristis IllegalArgumentException

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Nekretnina.java
> +            System.out.println("Greska, niste pravilno uneli podatke.");
Definisi static final field za ovu poruku(pogotovo to istu imas u jos jednoj klasi)

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Nekretnina.java
> +                System.out.println("Postoje samo zone 1, 2, 3 i 4");
static final String

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Stan.java
> +            System.out.println("Greska, niste pravilno uneli podatke.");
Ponavlja se isti string na vise mesta, da li moze da se nekako definise na jednom mestu?

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Kuca.java
> +    }
just for fun, uradi koristeci string builder

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Kuca.java
> +        return "Adresa kuce je: " + adresa + ". Zona je: " + zona + ". Kvadratura kuce je: " + kvadratura
Fali merna jedinica za kvadraturu

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Stan.java
> +    }
Probaj StringBuilder

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Stan.java
> +        return "Adresa stana je: " + adresa + ". Zona je: " + zona + ". Kvadratura stana je: " + kvadratura
merna jedinica za kvadraturu

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/StandardniUlaz.java
> +package zadatak1;
Obrisi i ovu klasu

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Vlasnik.java
> +    public String getImePrezime() {
Koliko vidim ovo su sve unused metode. Izbegavaj da ostavljas kod koji se nigde ne koristi.

2019-10-08 15:01 UTC, BoskoNikolic commented on src/zadatak1/Vlasnik.java
> +        return "Ime i prezime vlasnika: " + imePrezime + ". JMBG: " + jmbg + ". Broj licne karte: " + brojLicneKarte;
Probaj stringBuilder

2019-10-08 15:05 UTC, JovanPEndava commented on src/zadatak1/Kuca.java
> +        if (povrsinaOkucnice >= 0) {
Da, tu sam mislio da pokrivam slucaj kada nema okucnice, pa bi korisnik ubacio 0.

2019-10-08 15:17 UTC, BoskoNikolic requested changes
.

2019-10-09 19:26 UTC, BoskoNikolic requested changes
Pogledaj nove komentare i pokusaj da ih ispravis.

Pogledaj Issue br. 1 i novi komentar koji sam dodao pa pokusaj da ga ispravis.

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Main.java
> +            System.out.println("Greska: " + iae1);
Stampaj samo poruku exception-a  iae1.getMessage()

Ovako trenutno izgleda tvoj output kad stampas gresku. 
Greska: java.lang.IllegalArgumentException: Greska pri unosu imena i prezimena vlasnika.

 java.lang.IllegalArgumentException je visak

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Main.java
> +            System.out.println("Greska: " + iae2);
iae2.getMessage()

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Main.java
> +            System.out.println("Greska: " + iae);
iae.getMessage()

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Main.java
> +            System.out.println("Greska: " + iae);
getMessage()

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Nekretnina.java
> +// Author: Jovan Penic
Ovo izbrisi posto imas autora navedenog u main klasi

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Nekretnina.java
> +            if (adresa != null && !adresa.isEmpty() &&  ! adresa.matches("(.*)[!@#$%^&*(){};:',<>?`~](.*)")) {
Napravi static final filed za regex

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Vlasnik.java
> +            if (!imePrezime.isEmpty() && ! imePrezime.matches("(.*)[!@#$%^&*(){};:',.<>?/`~\\d](.*)")) {
static final za regex

 imePrezime.matches("^[a-zA-Z'\\-\\s]+$")) izgleda mnogo lepse a plus moze i da se proda u Irskoj ;)  

https://stackoverflow.com/questions/44420498/java-android-regex-expression-to-allow-names-that-may-have-apostrophe-and-or-hyp

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Vlasnik.java
> +            if (jmbg.length() == 13 && !(jmbg.matches("(.*)\\D(.*)"))) {
napravi static final za regex

zar nije bilo lakse    && (jmbg.matches([0-9]+)) ?

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Vlasnik.java
> +            if (brojLicneKarte.length() == 9 && !(brojLicneKarte.matches("(.*)\\D(.*)"))) {
Da si napravio static final za regex mogao si da ga iskoristis i ovde.

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Vlasnik.java
> +        StringBuilder sb1 = new StringBuilder();
Trudi se da koristis opisnije nazive promenljivih. 

ovde ti i ne treba nova promenljiva, mogao si odmah da uradis return new StringBuilder(...);

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Stan.java
> +        StringBuilder sb = new StringBuilder();
Ime promenljive gledaj da ti bude vise opisno :)

ovde ti i ne treba nova promenljiva, mogao si odmah da uradis return new StringBuilder(...);

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Kuca.java
> +        StringBuilder sb = new StringBuilder();
Nema potrebe da definises promenljivu, odmas vrati vrednost

return new StringBuilder(...);

2019-10-09 19:26 UTC, BoskoNikolic commented on src/zadatak1/Main.java
> +            System.out.println("Greska: " + iae2);
4 puta u ovoj klasi ti se ponavlja sting "Greska: " . Mogao si da napravis static final String i iskoristis ga svuda.

2019-10-10 14:40 UTC, BoskoNikolic approved these changes

2019-10-10 14:41 UTC, merged